import Header from "./header";
import Footer from "./footer";
import Head from "next/head";

interface Props {
  children: React.ReactNode;
}
const Layout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Landing booking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main> {children} </main>
      <Footer />
    </>
  );
};
export default Layout;
